### ISSUE TITLE
Uninitialized constant Hocon

### ISSUE THREAD

**Issue by juame** [puppetlabs/puppetlabs-hocon#22]
I always get the error message `Could not evaluate: uninitialized constant Hocon`. 

```
[root@puppet ~]# puppet apply /etc/puppet/modules/hocon/tests/hocon_setting.pp --noop
Notice: Compiled catalog for puppet.fqdn in environment production in 0.06 seconds
Error: /Stage[main]/Main/Hocon_setting[sample setting]: Could not evaluate: uninitialized constant Hocon
Notice: /Stage[main]/Main/Hocon_setting[sample setting2]: Dependency Hocon_setting[sample setting] has failures: true
Warning: /Stage[main]/Main/Hocon_setting[sample setting2]: Skipping because of failed dependencies
Notice: /Stage[main]/Main/Hocon_setting[sample setting3]: Dependency Hocon_setting[sample setting] has failures: true
Warning: /Stage[main]/Main/Hocon_setting[sample setting3]: Skipping because of failed dependencies
Notice: Finished catalog run in 0.05 seconds
```

puppet and ruby version:

```
Debug: Runtime environment: puppet_version=3.8.2, ruby_version=2.0.0, run_mode=user, default_encoding=UTF-8
```

Does someone have the same issue?
Thanks!

**Comment by juame** [comment]
It works with puppet 4.2.1.
Can you please verify if it should work with 3.x, too (metadata.json)?

**Comment by cprice404** [comment]
You've installed the gem, I presume?  It's possible that we pre-packaged the gem with 4.x but not with 3.x?

@fpringvaldsen I have a vague recollection of there being some feature that didn't work on 3.x, but I can't remember what it was?

**Comment by juame** [comment]
@cprice404 I'm using the RPMs (puppet / puppet-agent).

**Comment by cprice404** [comment]
@juame right, what I'm suggesting is that maybe the puppet-agent RPMs include the hocon gem, and the puppet 3.x RPMs do not.  If that's the case you would need to install the gem before the module would work.  So, try 'gem list' or '/opt/puppet/bin/gem list' and see if you see the HOCON gem in the output.

**Comment by juame** [comment]
@cprice404 you're right:
```
/opt/puppetlabs/bin/puppet --version
4.2.1
/opt/puppetlabs/puppet/bin/gem list hocon
*** LOCAL GEMS ***
hocon (0.9.2)
```
So, users of puppet 3.x.x would have to install the hocon gem: `gem install hocon`

**Comment by joshcooper** [comment]
Related issue, it's not possible to install the `hocon` gem and use this module in the same run:

```puppet
package { 'hocon':
  ensure   => present,
  install_options => ['--no-ri', '--no-rdoc'],
  provider => puppet_gem,
}
hocon_setting { 'name':
  ensure  => present,
  path    => '/etc/puppetlabs/puppetserver/conf.d/puppetserver.conf',
  setting => 'section.name',
  value   => 'value',
  require => [
    Package['hocon'],
   ]
}
```

```
$ puppet apply manifest.pp
...
Error: /Stage[main]/Main/Hocon_setting[name]: Could not evaluate: uninitialized constant Hocon
```

because the provider is not confined based on the `hocon` feature. As a result, the agent doesn't know to reload the gem cache due to the feature becoming true during the run. I'll submit a PR for that.

**Comment by joshcooper** [comment]
Filed as https://tickets.puppetlabs.com/browse/HC-46 and submitted a PR in https://github.com/puppetlabs/puppetlabs-hocon/pull/28
